#!/usr/bin/python3
import sys
import os

def factorize(number):
    divis = 2

    while number > 1:
        if number % divis == 0:
            factor = number // divis
            return factor, divis
        divis += 1

    raise ValueError(f"Cannot factorize {number}")

def factorize_file(file_p):
    try:
        with open(file_p, 'r') as file:
            for x in file:
                number = int(x.strip())
                try:
                    factor, divis = factorize(number)
                    print(f"{number}={factor}*{divis}")
                except ValueError as ve:
                    print(f"Error: {ve}")
    except FileNotFoundError:
        print(f"Error: File '{file_p}' not found.")
        sys.exit(1)
    except Exception as e:
        print(f"error reading file: {e}")
        sys.exit(1)

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        sys.exit(1)

    file_p = sys.argv[1]
    if not os.path.isfile(file_p):
        print(f"Error: File '{file_p}' not found.")
        sys.exit(1)

    factorize_file(file_p)

