#!/usr/bin/python3
import sys

def factorize(number):
    divis = 2

    while number > 1:
        if number % divis == 0:
            factor = number // divis
            return factor, divis
        divis += 1

def factorize_file(file_p):
    with open(file_p, 'r') as file:
        for x in file:
            number = int(x.strip())
            factor, divis = factorize(number)
            print(f"{number}={factor}*{divis}")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        sys.exit(1)

    file_p = sys.argv[1]
    factorize_file(file_p)

