#!/usr/bin/python3
import sys

def factorize(number):
    divis = 2
    factors = []

    while number > 1:
        if number % divis == 0:
            factors.append(divis)
            number //= divis
        else:
            divis += 1

    return factors

def find_prime_pairs(factors, original_number):
    for i in range(len(factors)):
        for j in range(i + 1, len(factors)):
            if factors[i] * factors[j] == original_number:
                print(f"{original_number}={factors[i]}*{factors[j]}")
                return

def factorize_file(file_p):
    with open(file_p, 'r') as file:
        for line in file:
            number = int(line.strip())
            factors = factorize(number)
            find_prime_pairs(factors, number)

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        sys.exit(1)

    file_p = sys.argv[1]
    factorize_file(file_p)

